### ISSUE TITLE
Setup instructions break because migration folder exists. 

### ISSUE THREAD

**Issue by RustyRaptor** [konishi-project/zimmerman#68]
When you go through the install instructions and get to
```bash
python3 manage.py db init
```
You will get an error
```
Error: Directory migrations already exists and is not empty
```

I was only able to fix by moving the migrations directory out of the root folder. I assume this is not intended behavior. What can be done about this? Why is the folder in there to begin with if it needs to be created during setup?

**Comment by X1Zeth2X** [comment]
The migrations folder is there for the Heroku deployment. Since initializing the db in Heroku would cause it to be removed (This is because of Heroku's ephemeral file system) after a certain amount of time.

In order for Flask Migrations to work in Heroku properly, the migrations should be created locally, commit them then deploy so that migrations would work, even then it would still cause issues because new migration versions created when running a migrate would also get deleted.

If running a custom server and migrations is in gitignore, this wouldn't be an issue.

**Comment by RustyRaptor** [comment]
got it. Anyway, it seems that moving the folder out doesn't cause any issues when testing locally so we can just use that as a workaround.

**Comment by X1Zeth2X** [comment]
Instead of a workaround, we can create a seperate branch specifically for Heroku.

**Comment by X1Zeth2X** [comment]
PR (#103) fixes this issue.
